### ISSUE TITLE
pgtrigger changes my django world...

### ISSUE THREAD

**Issue by rrauenza** [Opus10/django-pgtrigger#10]
....for the better.

I refuse to insert raw sql migrations into my migrations because I want everything captured in the models.  The hoops I have jumped through to get composite keys to work with django2.2's constraint system, or create unique together's, or "clever" multi table inheritance.  It left me feeling kinda queasy.

This package opens a completely new dimension to the things I can do to enforce integrity.  I hate doing it in python, although most people insert data from my REST API, so I can enforce it there... but ... triggers are really the right answer here! 

Thank  you, thank you, thank you!

**Comment by wesleykendall** [comment]
@rrauenza thanks so much for the feedback! `django-pgtrigger` similarly helped changed my way of thinking about database integrity (and history tracking - https://github.com/jyveapp/django-pghistory). So many times we try to enforce database integrity in the application layer, and I'm glad that we could make a tool that allows them to be easily created alongside Django models.

I can't tell you how many projects I have now where the checks I used to enforce in software (signals, models, etc) are now in a simple trigger that has 100% reliability, and this includes state transitions, some auto-derived fields, soft deletes, etc. If you have a common pattern that might be applicable to a wide array of use cases, feel free to suggest it and maybe we can try to put it in as a core trigger.

Thanks again!

**Comment by rrauenza** [comment]
When I saw your video and you mentioned the "grid" of history/audit tools I knew exactly what grid you were referring to.  I'm on my third package from there... each has its flaws.  I hope to someday try the one based on pgtriggers now.

Also maybe add soft delete as well...

**Comment by rrauenza** [comment]
CompositeKeys in Django isn't supported, so I hacked something in to enforce referential constraints.  But it kind of messes up migrations due to ordering (you sometimes have to move them to the end of the migration script.)   I'm wondering now if this would be a better fit for a trigger until Django supports Composite Keys directly.

My constraint wrapper: 

```
CompositeForeignKey(
                fields=("myf1", "myf2"),
                to_model="OtherModel",
                to_fields=("other1", "otherf2"),
            ),
```
 
Postgres forces you to have an index on the to_model to support the to_fields ... so that is a risk of using the trigger:  you might forget to make the index to make the enforcement efficient.

...But this could be added to pgtriggers as well to emulate.     Just an idea if you're looking to expand.  I'm sure I can make my own wrapper as well!

**Comment by wesleykendall** [comment]
@rrauenza thanks for the ideas and suggestions! If you do feel like a composite foreign key is something we could implement in pgtrigger without too much of a fuss, feel free to open another issue specifically for it. I'm not totally sure how the implementation would work off the top of my head, but open to more ideas/discussion.

Going through the issues and clearing out some of them for now
