### ISSUE TITLE
Add option to silence Logger when used with pytest

### ISSUE THREAD

**Issue by GNajeraAdv** [Opus10/django-pgtrigger#118]
Hi! When using in a project that utilizes "pytest" and PyCharm, the initial loading screen can be littered with lots of logs when installing triggers. I currently solve this by commenting out the following "LOGGER" statement:

https://github.com/Opus10/django-pgtrigger/blob/9cf9e61f65f5bb5c95756e4e645cafe6e582b097/pgtrigger/installation.py#L28-L32

Would it be possible to signal to silence the usage of Logger when setting up?

**Comment by wesleykendall** [comment]
You can also silence output for pytest with `--no-capture` - https://stackoverflow.com/questions/67533831/disable-printing-of-log-output-on-console-using-pytest

**Comment by GNajeraAdv** [comment]
Thanks for everything you do, Wesley! I didn't see your June-2023 reply, but that's pretty much what I ended up doing
