### ISSUE TITLE
Django 5.1 migration dependencies are now namedtuples

### ISSUE THREAD

**Issue by shangxiao** [Opus10/django-pgtrigger#148]
Django 5.1 switched to [namedtuples for migration dependencies](https://github.com/django/django/commit/7dd3e694db17bc34f9ce73e516f853ebd16e19e7).

pgtrigger's [migration patching will also need to be updated 👍](https://github.com/Opus10/django-pgtrigger/blob/3c2669bfb97500fc53edeefa981fa74da5412067/pgtrigger/migrations.py#L148)

**Comment by wesleykendall** [comment]
fixed in v4.12
