### ISSUE TITLE
[Question] Is this a usecase for django-pgtrigger?

### ISSUE THREAD

**Issue by simkimsia** [Opus10/django-pgtrigger#18]
Hi there, 

I need to make a pg trigger and I am using Django 2.2

the use case is like this:
1. i have auto primary key `id` is integer in the table called `teams`
2. i have another field called `business_identifier` that needs to be based on id value like this "TEAM000007"

I wanted to use trigger to autogenerate the values for `business_identifier` based on the id. 

So if I insert a new row, the auto primary key will auto fill in the id and i hope that the `business_identifier` will also auto update.

I have the sql code for postgres

```
CREATE OR REPLACE FUNCTION team_insert() RETURNS trigger AS $emp_stamp$
     BEGIN
         NEW.business_identifier:= 'TEAM' || LPAD(NEW.id::text, 6, '0');
         RETURN NEW;
     END;
$emp_stamp$ LANGUAGE plpgsql;

CREATE TRIGGER team_insert BEFORE INSERT OR UPDATE ON teams FOR 
 EACH ROW EXECUTE PROCEDURE team_insert();
```

How do I do this using django-pgtrigger?

**Comment by tomage** [comment]
Without testing it, perhaps something like:
```
@pgtrigger.register(
    pgtrigger.Trigger(
        name='set_team_identifier',
        operation=pgtrigger.Update | pgtrigger.Insert,
        when=pgtrigger.Before,
        func='NEW.business_identifier:= 'TEAM' || LPAD(NEW.id::text, 6, '0'); RETURN NEW;',
    )
)
class YourModel(Model):
    ....
```

That said, there's also a new feature in PG 12 called "generated column" (https://www.postgresql.org/docs/12/ddl-generated-columns.html) which might do the trick for you. Unfortunately, there's no Django ORM support for those as far as I know (there's been some talk on it, but I really haven't dug in: https://code.djangoproject.com/ticket/31565).

As an alternative I'd also try push back on it as much as possible and see if there are some alternative ways to get around it (i.e. ask your analysts/engineers to find ways to use the ID column directly) - but there may be totally valid reasons for why this isn't feasible. I always get a bad feeling when I'm asked to add data redundancy like this, but sometimes one just gotta do it :)

Hope this helps!

**Comment by simkimsia** [comment]
I'll give this a shot later today or tomorrow

As for checking whether it's necessary I agree that's the bigger question

I was reluctant to add this field to be frank but it seems required for now

**Comment by tomage** [comment]
> I'll give this a shot later today or tomorrow
> 
> As for checking whether it's necessary I agree that's the bigger question
> 
> I was reluctant to add this field to be frank but it seems required for now

Yeah - sometimes it's really just the best way forward for now.. Bit of redundancy could end up saving a lot of time for other people/groups and give some clarity as well. I know that in my main project, I for sure got plenty of that going around :)

Feel free to ping me if you can't it working!

**Comment by simkimsia** [comment]
> Feel free to ping me if you can't it working!

@tomage I think this doesn't really work. Not sure where I went wrong.

Django 2.2.19
pgtrigger 2.3.0
postgres 10.13

```
@pgtrigger.register(
    pgtrigger.Trigger(
        name="set_warehouse_business_identifier",
        operation=pgtrigger.Update | pgtrigger.Insert,
        when=pgtrigger.Before,
        func="NEW.business_identifier:= 'WH' || LPAD(NEW.id::text, 6, '0'); RETURN NEW;",
    )
)
@reversion.register()
class Warehouse(
    ComputedFieldsModel,
    DirtyFieldsMixin,
    TimeStampedModel,
    SoftDeletableModel,
    PersonStampedModel,
    OrganizationOwnedModel,
):

    # making this nullable might make it easier to do the postgres trigger on create-update
    business_identifier = models.CharField(
        max_length=255, editable=False, unique=True, null=True
    )
    name = models.CharField(max_length=255)
    address = models.TextField()
```

the migration file was

```python
# Generated by Django 2.2.19 on 2021-03-18 05:54

import computedfields.resolver
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20190925_0313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rea', '0126_auto_20210317_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('business_identifier', models.CharField(editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rea_warehouse', related_query_name='query_created_rea_warehouses', to=settings.AUTH_USER_MODEL)),
                ('forked_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forks', to='rea.Warehouse')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_rea_warehouse', related_query_name='query_last_edited_rea_warehouses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rea_warehouse_organization', to='organizations.Organization')),
            ],
            options={
                'ordering': ('business_identifier',),
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]

```

**Comment by wesleykendall** [comment]
@simkimsia I know this issue is a bit old, but can you clarify what went wrong and if you are still experiencing it? Currently django-pgtrigger does not install triggers in migrations, so it will not appear in a migrations file. We are working towards making it compatible with django migrations in the future though. For now, just `manage.py migrate` will install the registered triggers.

I believe the example @tomage gave should have worked if your previous trigger definition was working

**Comment by simkimsia** [comment]
It doesn't work but the need for this has also gone down for the time being. In this case, I will temporarily close this issue and revisit it when the need for this goes back up again.

Thank you @wesleykendall
