### ISSUE TITLE
DROP TRIGGER is executed twice when trigger definition changes

### ISSUE THREAD

**Issue by igavriil** [Opus10/django-pgtrigger#193]
When there is an existing trigger on a model and the trigger is altered (in any way)
the migration mechanism generates a migration that:
* Drops the trigger via `RemoveTrigger` operation
* Creates the trigger via `AddTrigger` operation

Before creating the new trigger a trigger with the same name [is dropped again ](https://github.com/Opus10/django-pgtrigger/blob/main/pgtrigger/compiler.py#L72)

Ideally in the migration we should only have the 
* `AddTrigger` operation which already drops any existing trigger

The issue lies [here](https://github.com/Opus10/django-pgtrigger/blob/main/pgtrigger/migrations.py#L201) as the "old" trigger is considered "removed" which generates the `RemoveTrigger` operation

**Comment by wesleykendall** [comment]
Is this causing issues for you or just a suggestion to avoid redundant operations?

**Comment by igavriil** [comment]
The latter. It's not causing issues at the moment. I am trying to work around another issue (https://github.com/Opus10/django-pgtrigger/discussions/191) and this behaviour was a bit unexpected

**Comment by wesleykendall** [comment]
Going to close this for now. The migration system integration is very complex. There's likely a good reason for dropping triggers in a separate step, and I imagine taking it out would potentially cause issues without much benefit. If there's a pretty noticeable performance degradation from having a redundant operation, happy to re-open
