### ISSUE TITLE
register trigger function in separate file

### ISSUE THREAD

**Issue by highpost** [Opus10/django-pgtrigger#21]
I have a PL/PGSQL trigger function `handle_new_row()` that I register manually with the `CREATE TRIGGER` command:
```
  CREATE TRIGGER mytrigger
    AFTER INSERT
    ON mytable
    FOR EACH ROW
    EXECUTE FUNCTION handle_new_row();
```
This works fine, but I would like to use `pgtrigger` to manage it with Django migrations. Is this possible? My trigger function is pretty elaborate so it seems better to leave it in a separate file rather than use the inline approach from the examples. Here is what I've tried:
```
@pgtrigger.register(
    pgtrigger.Trigger(
        name       = 'handle_new_row',
        operation  = pgtrigger.Insert,
        level      = pgtrigger.Row,
        when       = pgtrigger.After,
        func       = (
                        Path(f'{os.environ["MYAPP"]}/sql/mytrigger.sql')
                          .read_text(encoding  = 'utf-8')
                     )
    )
)
class MyTable(Model):
  ...
```
but this blows up with:
```
psycopg2.errors.FunctionExecutedNoReturnStatement:
control reached end of trigger procedure without RETURN
CONTEXT:  PL/pgSQL function pgtrigger_handle_new_row_008cd()
```

**Comment by wesleykendall** [comment]
@highpost it seems that the code you wrote is fine, but the trigger itself doesn't have a `RETURN` at the end. Does your trigger SQL have `RETURN NEW;` at the end of it? I believe that will fix this particular error

**Comment by wesleykendall** [comment]
@highpost closing out this issue for now. I'm pretty certain the answer I provided fixes the particular issue you experienced though. Feel free to comment if I should re-open!
