### ISSUE TITLE
Tuttorial issues

### ISSUE THREAD

**Issue by terkin** [Opus10/django-pgtrigger#22]
Looks like at a lot of your examples and at tutorial https://wesleykendall.github.io/django-pgtrigger-tutorial/#setup name attribute is not set, its confusing cause its required attribute and when I tried some examples from tutorial I ran into issue

`
File "/Users/XXX/venv/lib/python3.8/site-packages/pgtrigger/core.py", line 424, in __init__
    raise ValueError('Trigger must have "name" attribute')
ValueError: Trigger must have "name" attribute
`

**Comment by wesleykendall** [comment]
Yea looks like I haven't updated that tutorial to the latest version. I blocked off some time on my calendar and will have this resolved on Aug 14. Appreciate you letting me know!

**Comment by wesleykendall** [comment]
Just updated the tutorial and verified things work with the latest version!
