### ISSUE TITLE
Trigger name is case sensitive

### ISSUE THREAD

**Issue by johacks** [Opus10/django-pgtrigger#23]
Today all my triggers where getting installed and then inmediately prunned.

This happens if the name of a trigger doesn't have all lowercase letters, as the trigger_id is stored in the database as lowercase, but it is returned with original uppercase letters in the *trigger.get_pgid* method. As a result, the *get_prune_list* function in *core.py*  retrieves first all of the installed triggers where the id's keep original uppercase letters and then don't match against the database current trigger id's, as they are stored with a lowercase conversion of the id.

I don't know if this is expected behaviour, but maybe it should be changed, or docummented in the docs (that the name parameter of trigger should be lowercase), as it was a little anoying having to debug source code.

**Comment by wesleykendall** [comment]
@johacks thanks for bringing this up. This sounds like an obvious error that needs to be fixed, and I believe it will be a pretty simple one. I blocked off time on my calendar on Aug 14 to check in on this and address it. Will either have a response or a PR then. Sorry for the delay!

**Comment by wesleykendall** [comment]
Addressed in https://github.com/Opus10/django-pgtrigger/pull/35

**Comment by johacks** [comment]
Many thanks for fixing the issue. This repository is very helpful, keep up the good work!
