### ISSUE TITLE
README snippets missing name kwarg

### ISSUE THREAD

**Issue by shangxiao** [Opus10/django-pgtrigger#28]
The examples in the README appear to be missing a `name` kwarg.

**Comment by wesleykendall** [comment]
Good catch! I'm doing a large cleanup of things on August 14 and will have it resolved then

**Comment by OJFord** [comment]
Also `func` is used in examples but not in the reference for `Trigger` args above.

**Comment by wesleykendall** [comment]
Fixed the README and broken doc examples in https://github.com/Opus10/django-pgtrigger/pull/35

Fixed the missing ``func`` docs in https://github.com/Opus10/django-pgtrigger/pull/34

Thanks!
