### ISSUE TITLE
Bug: pgtrigger.core.Trigger.render_ignore  ignores the schema

### ISSUE THREAD

**Issue by GigiusB** [Opus10/django-pgtrigger#37]
The trigger can't find the function if the model is in a schema: the _pgtrigger_should_ignore should be prefixed with the schema name

**Comment by wesleykendall** [comment]
@GigiusB thanks for letting me know. I'm going to set up a multi-schema test env and reproduce this

**Comment by wesleykendall** [comment]
@GigiusB this bug is addressed in #80 

I made it so that `_pgtrigger_should_ignore` is always installed in the public schema by default and referenced with a fully-qualified path. The schema can be changed by overriding ``settings.PGTRIGGER_SCHEMA``.

Will let you know when it is released

**Comment by wesleykendall** [comment]
Fixed in version 4
