### ISSUE TITLE
ModuleNotFoundError: No module named 'pgconnection'

### ISSUE THREAD

**Issue by tmarshall** [Opus10/django-pgtrigger#39]
The `pgconnection` module is only used within `_inject_pgtrigger_ignore`, but is imported top-level. This causes a dependency issue when it's not installed in an existing project.

Thoughts on moving this import into the function itself, so that it is only a required dependency when needed?

**Comment by wesleykendall** [comment]
@tmarshall the django-pgconnection dependency was dropped in django-pgtrigger version 3, so this should no longer be an issue!
