### ISSUE TITLE
pgtrigger doesn't play nicely (i.e., ignore) other non postgres dbs

### ISSUE THREAD

**Issue by rrauenza** [Opus10/django-pgtrigger#41]
I have a mysql db I use readonly as well as a sqlite db I use in testing ... pgtriggers tries to query them to see if they have any triggers that need to be purged.

We end up falling into:

```
1   948     if isinstance(database, str):
    949         databases = [database]
    950     else:
    951         databases = database or settings.DATABASES
    952 
```

And using the settings.DATABASES.  Then we fail when the SELECT is invalid for those other non postgres dbs.

Looking at the code I don't see a way to ignore other databases as the code is...  I'm not sure how you would want to fix.    I'd say look at ENGINE="django.db.backends.postgresql_psycopg2" except, that I have a wrapper ("pg_unlogged") around the standard postgres engine to force unlogged transactions during testing.  

Ah.. this might help:

https://stackoverflow.com/a/18849255/2077386

```
>>> from django.db import connection
>>> connection.vendor
'postgresql' or 'sqlite'
```

**Comment by wesleykendall** [comment]
@rrauenza these issues should be resolved now! Version 3 is also integrated with the migration system and ignores migrating triggers when the DB vendor is not postgres. This in theory should allow you to even run your test suite against sqllite (of course keeping in mind that triggers wont be installed)

**Comment by mrvisiol** [comment]
Looks like pghistory still has this problem? Our test database is also SQLite, and I noticed no issues when I included pgtrigger. When I started using pghistory, migration dependencies include "0005_events_middlewareevents", which creates functions used in the history tracking, but cannot be created in SQLite. How difficult would it be to make a similar change/fix in pghistory? Thank you!
