### ISSUE TITLE
Changes to trigger conditions require uninstall/reinstall in order to work

### ISSUE THREAD

**Issue by callumenator** [Opus10/django-pgtrigger#52]
Given an existing trigger on a model, updating the condition for that trigger and running a migrate will not update the trigger definition in the database. The steps as far as I can see are:

add trigger to model, with condition A (e.g. `Q(old__field="a")`)
`run ./manage.py install` <- trigger now exists in db with condition A
change the trigger condition to B (e.g. `Q(old__field="b")`)
`run ./manage.py pgtrigger ls` <- pgtrigger detects that the trigger condition has changed, lists trigger as OUTDATED
`run ./manage.py install` <- pgtrigger says it has installed the new trigger, but the DB does not get updated

Since the trigger already exists, the install of the new trigger fails, but the generated sql https://github.com/Opus10/django-pgtrigger/blob/3ef7e0361901d0b9548ad526768a2fe5412e5d1d/pgtrigger/core.py#L574 handles the exception, so it fails silently. After the failure though, the trigger hash is still updated to the new value https://github.com/Opus10/django-pgtrigger/blob/3ef7e0361901d0b9548ad526768a2fe5412e5d1d/pgtrigger/core.py#L664, so if you run `ls` again, it does not think the trigger is outdated.

I wonder if on detecting that the trigger is outdated the first time, the generated trigger sql should first drop the trigger if it exists, and then recreate? Currently the only way to ensure that the trigger is updated is to uninstall it, and then (re)install it.

Note that this showed up through django-pghistory, where adding a new field to a model would not result in changes to that new field being tracked if it was the only field that changed, since the trigger condition only compared the fields that existed before the new one was added (if you _remove_ a field from the model however, that automatically drops the existing trigger, since it referenced the removed field, and so the subsequent install would result in a correctly updated trigger condition).

**Comment by wesleykendall** [comment]
@callumenator thanks for bringing this up. It sounds like a potentially serious bug. There have been several upgrades to pgtrigger to integrate it with the migration system. Let me see if this might have resolved it. Will report back on this ticket

**Comment by wesleykendall** [comment]
Just fixed this with https://github.com/Opus10/django-pgtrigger/issues/52, which will be merged soon.

**Comment by wesleykendall** [comment]
Fix is deployed in version 3.3
