### ISSUE TITLE
Triggers on Abstract Models

### ISSUE THREAD

**Issue by jzmiller1** [Opus10/django-pgtrigger#57]
Should it be possible to use triggers on abstract models in some way or is that unsupported?  It doesn't seem possible but I wanted to make sure I'm not just missing something in the options somewhere.

The following example code leads to an error:

```python

import pgtrigger
from psqlextra.models import PostgresModel

@pgtrigger.register(
    pgtrigger.Protect(
        name='read_only',
        operation=pgtrigger.Update,
        condition=pgtrigger.Q(old__created_at__df=pgtrigger.F('new__created_at'))
    )
)
class SaasBaseModel(PostgresModel):

    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class ExampleModel(SaasBaseModel):
    color = models.CharField(max_length=64)
```

```
Traceback (most recent call last):
  File "C:\X\lib\site-packages\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "common_saasbasemodel" does not exist
CONTEXT:  SQL statement "CREATE TRIGGER pgtrigger_read_only_4072d
                    BEFORE UPDATE ON common_saasbasemodel
                    
                    FOR EACH ROW WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))
                    EXECUTE PROCEDURE pgtrigger_read_only_4072d()"
PL/pgSQL function inline_code_block line 2 at SQL statement
```

**Comment by jzmiller1** [comment]
I was unable to come up with anything fancier so I ended up doing this.  

Adding list of triggers to the base model:

```
class SaasBaseModel(PostgresModel):

    class Meta:
        abstract = True


    created_at = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    TRIGGERS = [
        pgtrigger.Protect(
            name='read_only',
            operation=pgtrigger.Update,
            condition=pgtrigger.Q(old__created_at__df=pgtrigger.F('new__created_at'))
        ),
    ]


class ExampleModel(SaasBaseModel):
    color = models.CharField(max_length=64)
```


Adding a util function to my common.utils:
```
def load_inherited_triggers(app):

    models_with_triggers = [m for m in app.get_models() if hasattr(m, 'TRIGGERS')]

    for m in models_with_triggers:
        for t in m.TRIGGERS:
            t.register(m)
```

Using the util function in my app configs:

```
from django.apps import AppConfig
from common.utils import load_inherited_triggers


class CommonConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'common'

    def ready(self):
        load_inherited_triggers(self)
```

**Comment by jzmiller1** [comment]
As of version 2.5.0 this is now handled by django-pgtrigger.  If the triggers are defined in the meta on the base class they are added to models that inherit.

**Comment by wesleykendall** [comment]
@jzmiller1 thanks for verifying abstract models work!

I'm going to re-open this for now and close it after I do the following:

1. Add it to the docs
2. Document the gotchas of inheriting model `Meta` classes. One needs to follow [the guide here](https://docs.djangoproject.com/en/3.2/topics/db/models/#meta-inheritance) if you declare `Meta` in the child, which could cause abstract triggers to be ignored.

I may consider displaying a warning if child triggers are not inherited and allowing it to be suppressed. I'm not totally sure yet though because Django doesn't do this for `indexes` or `constraints` on abstract models

**Comment by wesleykendall** [comment]
Added to the docs in v4. I opened #81 to add some additional warnings for triggers that arent inherited in child classes

**Comment by jzmiller1** [comment]
Thanks!
