### ISSUE TITLE
can't create Constraint Trigger

### ISSUE THREAD

**Issue by likecodingloveproblems** [Opus10/django-pgtrigger#79]
I can't create `CONSTRAINT TRIGGER` and also set `DEFERRABLE INITIALLY DEFERRED` settings.

**Comment by wesleykendall** [comment]
Did you read [this section of the docs](https://django-pgtrigger.readthedocs.io/en/latest/deferrable.html) on how to do this? Or did you try it and receive an error?

It's fully supported by the library by using the ``timing`` argument of the trigger. For example:

```
class MyModel(Model):
    class Meta:
        triggers = [
            pgtrigger.Trigger(name="constraint_trigger", timing=pgtrigger.Deferred, ...)
        ]
```

**Comment by wesleykendall** [comment]
Going to close this since I believe it's been answered. Feel free to re-open you're still having issues
