### ISSUE TITLE
Support for the DECLARE part of the trigger function

### ISSUE THREAD

**Issue by pbc** [Opus10/django-pgtrigger#9]
When trying to write a trigger function, I have noticed that I have no way to specify the `DECLARE` part and from what I can see the current code base has some initial support for this functionality, but the `def get_declare(self, model)` method on the `Trigger` class , just returns an empty list.

Would it be possible to add full support for the `DECLARE` section?

**Comment by wesleykendall** [comment]
@pbc yea so far I have only ran into the use case where I had to override the variable declaration of the DECLARE statement, hence the `get_declare` returning a list of tuples. However, there is a `render_declare` at https://github.com/jyveapp/django-pgtrigger/blob/f20d55f52fafef46002f8f8f922647f8545dd840/pgtrigger/core.py#L470 on the trigger that returns the SQL used in the DECLARE section.

Can you elaborate on your use case a bit? I'm curious if there might be a more elegant way to do it, or perhaps your use case might be more of an advanced one

**Comment by pbc** [comment]
@wesleykendall I think I got confused by the fact that you are able to define the whole trigger using parameters accepted by the base `Trigger` class, but if you want to use the DECLARE section, then you actually have to create a subclass, which is rather unusual because you would expect the parameters to be.... "parameterised" :smile: 

If this is a conscious design decision then we can close this issue, but I think it might cause an explosion of classes because you're forced to subclass `Trigger` for each different trigger function.

**Comment by OJFord** [comment]
Perhaps this has changed since, or I'm not understanding the 'full support' you're after, but I used `func="DECLARE ... BEGIN ... END"` no problem before seeing this issue. Seems to work fine.

**Comment by wesleykendall** [comment]
@pbc apologies for the long delay here. I see exactly what you mean, and I will follow up with a PR to make it part of the base class.

@OJFord , the main part that renders the trigger SQL is at https://github.com/Opus10/django-pgtrigger/blob/1b84a2b4be589917417811301b921acbcd4a2e2b/pgtrigger/core.py#L569, which looks like this:

```
def render_func(self, model):
        """Renders the trigger function SQL statement"""
        return f'''
            CREATE OR REPLACE FUNCTION {self.get_pgid(model)}()
            RETURNS TRIGGER AS $$
                {self.render_declare(model)}
                BEGIN
                    {self.render_ignore(model)}
                    {self.get_func(model)}
                END;
            $$ LANGUAGE plpgsql;
        '''
```

Although I haven't tried this myself, I assume that you might be creating a trigger with a nested `DECLARE ... BEGIN ... END`. Assuming this is valid syntax, it probably just works for your situation.

@pbc the declaration syntax looks pretty straightforward, so I was planning to implement it similar to what `get_declare` already returns. i.e. a list of (variable names, type) tuples. For example:

```
Trigger(
    func=''' custom func ''',
    declare=[
        ('custom_variable_name', 'BOOLEAN')
    ]
)
```

**Comment by wesleykendall** [comment]
Fixed in https://github.com/Opus10/django-pgtrigger/pull/34

``declare`` is now part of ``__init__``, and users can still override `get_declare`, especially if they have a dynamic declare syntax

**Comment by wesleykendall** [comment]
Also updated the docs in the tutorial to mention this is a top-level attribute now
