### ISSUE TITLE
Error column "tgparentid" does not exist #95

### ISSUE THREAD

**Issue by duducp** [Opus10/django-pgtrigger#96]
Hello everyone, after upgrading django-pgtrigger 3.4.0 to 4.3.3 I started getting the following error:

```
django.db.utils.ProgrammingError: column "tgparentid" does not exist
LINE 5:                       tgparentid = 0 AND
```

This error is being generated from this part of the code: https://django-pgtrigger.readthedocs.io/en/latest/_modules/pgtrigger/installation.html?highlight=tgparentid#

Evaluating the versions, the problem starts from version 4.3.0. Following as described in the tag https://github.com/Opus10/django-pgtrigger/releases/tag/4.3.0 I ran the command `python manage.py pgtrigger install` but soon got the error.

**Comment by wesleykendall** [comment]
@duducp what version of Postgres do you use? I have a feeling that this column may only be available in later versions of postgres that support partitioning.

Let me know and I will update the test suite to run against your version and make sure this is corrected. Thanks for reporting!

**Comment by wesleykendall** [comment]
I checked, and it looks like this is a Postgres>=13 column. I should be able to get in a fix this weekend. Will be better to run the test suite against many postgres versions

**Comment by wesleykendall** [comment]
Turned out to be a pretty easy fix in #98 that will be merged soon. I tested locally against Postgres 12 and verified the bug was fixed.

I created #99 as a follow-up ticket to test against multiple versions of Postgres.

**Comment by wesleykendall** [comment]
Fix deployed in version 4.4. Thanks for reporting!

**Comment by carlosdorneles-mb** [comment]
Hello @wesleykendall, I'm using Postgres version 11.2. Thanks for correcting.

**Comment by duducp** [comment]
Hello @wesleykendall, I'm using Postgres version 11.2. Thanks for correcting.
